Document: upditool
Title: Debian upditool Manual
Author: <insert document author here>
Abstract: This manual describes what upditool is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/upditool/upditool.sgml.gz

Format: postscript
Files: /usr/share/doc/upditool/upditool.ps.gz

Format: text
Files: /usr/share/doc/upditool/upditool.text.gz

Format: HTML
Index: /usr/share/doc/upditool/html/index.html
Files: /usr/share/doc/upditool/html/*.html
